[default_apps]
teams = "teams-for-linux --enable-features=UseOzonePlatform --ozone-platform=wayland --url {meeting_url}"
calendar_client = "thunderbird"
terminal = "wezterm"

[debug]
try_suppress_errors     =   false                                   
try_suppress_warnings   =   true                                   
app_paths               =   ["~/.local/share/applications/"]        

[units]
lengths                 =   "meter"
weights                 =   "kg"
volumes                 =   "l"

[appearance]
width                   = 900                                       
height                  = 593                                       
gsk_renderer            = "cairo"                                   
recolor_icons           = false                                     
icon_paths              = [ "~/.config/sherlock/icons"]             
icon_size               = 64                                      
search_icon             = false                                    
use_base_css            = true

[behavior]
caching                 =   true                                    
cache                   =   "~/.cache/sherlock_desktop_cache.json"  
daemonize               =   false                                
animation               =   true                                  

[binds]
prev                    =   "None"                                  
next                    =   "None"                                  
modifier                =   "alt"                               

[files]
fallback                =   "~/.config/sherlock/fallback.json"
css                     =   "~/.config/sherlock/main.css"
alias                   =   "~/.config/sherlock/sherlock_alias.json"
ignore                  =   "~/.config/sherlock/sherlockignore"
